### PR TITLE
2531 HateoasSortHandlerMethodArgumentResolver should append * to the …

### PR DESCRIPTION
**Pull request by motofix**
Fix for #2531

### CODE REVIEW

**Comment by reda-alaoui** [comment]
The goal should be to raise the pull request on the original repository.
At least, tests are missing.

**Review by reda-alaoui — CHANGES_REQUESTED** [review]
The goal should be to raise the pull request on the original repository.
At least, tests are missing.

**Comment by reda-alaoui** [comment]
@motofix please open immediatly a PR on https://github.com/spring-projects/spring-data-commons

**Comment by motofix** [comment]
Done
https://github.com/spring-projects/spring-data-commons/pull/2945

**Pull request merged**
